import {useEffect,useRef,useState} from 'react';
import {Cat as CatIcon,Search,RefreshCw,MapPin,ExternalLink,Heart,SlidersHorizontal,ArrowUpRight,Clock,Link as LinkIcon,X,ChevronDown} from 'lucide-react';
import type {Cat,Inventory} from './types';
import {defaults,readFilters,writeFilters,filterCats,ageLabel,type Filters} from './search';
const date=(value:string|null)=>value?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZone:'America/Phoenix'}).format(new Date(value)):'Not yet checked';
const safeUrl=(s:string|null)=>{try{const u=new URL(s||'');return ['https:','http:'].includes(u.protocol)?u.href:undefined;}catch{return undefined;}};
const isStale=(s:string)=>Date.now()-Date.parse(s)>86400000;
const storageKey='soul-cat:saved';
function initialSaved(){try{const v=JSON.parse(localStorage.getItem(storageKey)||'[]');return new Set<string>(Array.isArray(v)?v.filter((x:unknown)=>typeof x==='string').slice(0,2000):[]);}catch{return new Set<string>();}}
function Card({cat,saved,onSave}:{cat:Cat;saved:boolean;onSave:()=>void}){
 const [broken,setBroken]=useState(false),photo=safeUrl(cat.photo),url=safeUrl(cat.adoptionUrl);
 return <article className="cat-card"><div className="cat-photo">{photo&&!broken?<img src={photo} alt={cat.name} loading="lazy" onError={()=>setBroken(true)}/>:<div className="no-photo"><CatIcon size={52}/><span>Photo not available</span></div>}<button className={`save-cat ${saved?'is-saved':''}`} aria-label={`${saved?'Unsave':'Save'} ${cat.name}`} aria-pressed={saved} onClick={onSave}><Heart size={20} fill={saved?'currentColor':'none'}/></button>{cat.availability==='not_listed'&&<span className="photo-label">No longer listed</span>}</div><div className="cat-body"><p className="shelter">{cat.shelter}</p><h3>{cat.name}</h3><p className="cat-age">{ageLabel(cat.ageMonths)} <span>•</span> {cat.sex.split('/')[0]}</p><p className="cat-breed">{cat.breed==='Unknown'?'Breed not listed':cat.breed}</p><p className="cat-place"><MapPin size={14}/>{cat.city!=='Unknown'?cat.city:'Ask rescue for location'}</p>{cat.coat!=='Unknown'&&<span className="coat-tag">{cat.coat}<span>Source label</span></span>}<details className="cat-more"><summary>About {cat.name}<ChevronDown size={14}/></summary><p className="description">{cat.description||'This source has not provided a description. Ask the rescue about personality, care and adoption requirements.'}</p><dl><dt>Location</dt><dd>{cat.location}</dd><dt>Adoption fee</dt><dd>{cat.adoptionFee||'Ask rescue'}</dd><dt>Animal ID</dt><dd>{cat.animalId}</dd><dt>First seen</dt><dd>{date(cat.firstSeen)}</dd><dt>Last seen</dt><dd>{date(cat.lastSeen)}</dd></dl><p className="muted">Confirm availability with the rescue before visiting.</p></details><div className="cat-bottom"><span className={isStale(cat.lastSeen)?'stale':'muted'}><Clock size={12}/>{isStale(cat.lastSeen)?'Check overdue':'Seen within 24h'}</span>{url&&<a href={url} target="_blank" rel="noopener noreferrer">{cat.sourceId==='saving-one-life'?`Find ${cat.name} on rescue page`:`Meet ${cat.name}`}<ArrowUpRight size={15}/></a>}</div></div></article>;
}
export default function App(){
 const [inventory,setInventory]=useState<Inventory|null>(null),[loadError,setLoadError]=useState(''),[notice,setNotice]=useState(''),[starting,setStarting]=useState(false);
 const [filters,setFilters]=useState<Filters>(()=>readFilters(location.search)),[saved,setSaved]=useState(initialSaved),[limit,setLimit]=useState(24),[storageError,setStorageError]=useState('');
 const [filterOpen,setFilterOpen]=useState(()=>window.innerWidth>700);
 const loading=useRef(false),mounted=useRef(true);
 async function load(){if(loading.current)return;loading.current=true;try{const r=await fetch('/api/inventory',{signal:AbortSignal.timeout(20000)});if(!r.ok)throw new Error('Could not load listings. Please try again.');const data=await r.json();if(mounted.current){setInventory(data);setLoadError('');}}catch{if(mounted.current)setLoadError('Could not load listings. Your last loaded results are still shown.');}finally{loading.current=false;}}
 useEffect(()=>{mounted.current=true;void load();return()=>{mounted.current=false;};},[]);
 const running=inventory?.runs[0]?.status==='running';
 useEffect(()=>{if(!running&&!starting)return;const timer=setInterval(()=>void load(),3000);return()=>clearInterval(timer);},[running,starting]);
 useEffect(()=>{const query=writeFilters(filters);history.replaceState(null,'',location.pathname+(query?'?'+query:'')+location.hash);setLimit(24);},[filters]);
 useEffect(()=>{const onPop=()=>setFilters(readFilters(location.search));addEventListener('popstate',onPop);return()=>removeEventListener('popstate',onPop);},[]);
 const patch=(value:Partial<Filters>)=>setFilters(f=>({...f,...value}));
 async function refresh(){setStarting(true);setNotice('Checking all connected rescues…');try{const response=await fetch('/api/refresh',{method:'POST',signal:AbortSignal.timeout(60000)});const body=await response.json();if(!response.ok)throw new Error(body.error||'Could not start the scan.');await load();setNotice('Scan finished. See source coverage for individual results.');}catch(e){setNotice(e instanceof Error?e.message:'Scan could not finish. Please check scan history.');}finally{setStarting(false);}}
 function toggleSaved(key:string){setSaved(current=>{const next=new Set(current);next.has(key)?next.delete(key):next.add(key);try{localStorage.setItem(storageKey,JSON.stringify([...next]));setStorageError('');}catch{setStorageError('Browser storage is unavailable. Your saved cats will last only for this session.');}return next;});}
 async function share(){const query=writeFilters(filters),url=location.origin+location.pathname+(query?'?'+query:'');try{await navigator.clipboard.writeText(url);setNotice('Search link copied. Saved cats stay private to this browser.');}catch{setNotice('Copy the address in your browser to share this search.');}}
 const cats=inventory?.cats||[],sources=inventory?.sources||[],visible=filterCats(cats,filters,saved);
 const cities=[...new Set(cats.map(c=>c.city))].sort(),coats=[...new Set(cats.map(c=>c.coat).filter(c=>c!=='Unknown'))].sort(),breeds=[...new Set(cats.map(c=>c.breed).filter(c=>c!=='Unknown'))].sort();
 const connected=sources.filter(s=>s.connected),failed=connected.filter(s=>s.status==='failed'),staleCount=cats.filter(c=>c.availability==='listed'&&isStale(c.lastSeen)).length;
 const ageNames:Record<string,string>={kitten:'Kittens · under 1 year',young:'Young · 1–2 years',adult:'Adults · 3–9 years',senior:'Seniors · 10+ years'};
 const chips=([['q',filters.q],['city',filters.city],['source',sources.find(s=>s.id===filters.source)?.name||filters.source],['age',ageNames[filters.age]],['sex',filters.sex],['breed',filters.breed],['coat',filters.coat]] as [keyof Filters,string][]).filter(([,v])=>!!v);
 return <><a className="skip-link" href="#results">Skip to cats</a><header className="topbar"><a className="brand" href="/" aria-label="Soul Cat home"><CatIcon size={28}/>Soul Cat</a><nav aria-label="Main navigation"><a href="#coverage">Our sources</a><button onClick={()=>patch({savedOnly:!filters.savedOnly})} aria-pressed={filters.savedOnly}><Heart size={17}/>Saved cats <span className="count">{saved.size}</span></button></nav></header><main>
 <section className="search-header"><div><p className="region"><MapPin size={15}/>Phoenix-area rescues</p><h1>Find your cat.</h1><p className="intro-copy">Different personalities. Every kind of coat. One place to start looking.</p></div><div className="refresh-area"><button className="scan-button" onClick={()=>void refresh()} disabled={starting||running}><RefreshCw size={16} className={starting||running?'spin':''}/>{starting||running?'Scanning…':'Scan now'}</button><span>{connected.length} connected rescues · {sources.length-connected.length} not integrated</span></div></section>
 <div className="search-bar"><Search size={21}/><label className="sr-only" htmlFor="cat-search">Search cats</label><input id="cat-search" type="search" placeholder="Search a name, breed, coat or keyword…" value={filters.q} onChange={e=>patch({q:e.target.value})}/><button aria-label="Share search" onClick={()=>void share()}><LinkIcon size={16}/><span>Share search</span></button></div>
 <div className="freshness"><span>Last complete check: <strong>{date(inventory?.lastSuccess||null)}</strong></span><span>Next: {inventory?.nextCheck?date(inventory.nextCheck):'Loading…'} <span className="muted">Phoenix time</span></span></div>
 {(notice||storageError)&&<div role="status" className="notice">{storageError||notice}<button aria-label="Dismiss message" onClick={()=>{setNotice('');setStorageError('');}}><X size={16}/></button></div>}
 {loadError&&<div role="alert" className="notice warning">{loadError}<button onClick={()=>void load()}>Retry</button></div>}
 <div className="browse-layout"><aside><details className="filter-panel" open={filterOpen} onToggle={e=>setFilterOpen(e.currentTarget.open)}><summary><SlidersHorizontal size={17}/>Filters<ChevronDown size={16}/></summary><div className="filter-content"><div className="filter-reset"><span>Make it your search</span><button onClick={()=>setFilters({...defaults,savedOnly:filters.savedOnly})}>Clear filters</button></div>
 <label>Age group<select value={filters.age} onChange={e=>patch({age:e.target.value})}><option value="">Any age</option>{Object.entries(ageNames).map(([v,label])=><option value={v} key={v}>{label}</option>)}</select></label><label className="check"><input type="checkbox" checked={filters.unknownAge} onChange={e=>patch({unknownAge:e.target.checked})}/>Include unknown ages</label>
 <label>City<select value={filters.city} onChange={e=>patch({city:e.target.value})}><option value="">All locations</option>{cities.map(c=><option key={c} value={c}>{c==='Unknown'?'Location not listed':c}</option>)}</select></label><label>Rescue<select value={filters.source} onChange={e=>patch({source:e.target.value})}><option value="">All connected rescues</option>{connected.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
 <label>Sex<select value={filters.sex} onChange={e=>patch({sex:e.target.value})}><option value="">Any sex</option><option value="female">Female</option><option value="male">Male</option><option value="unknown">Not listed</option></select></label>
 <label>Breed<select value={filters.breed} onChange={e=>patch({breed:e.target.value})}><option value="">Any breed</option>{filters.breed&&!breeds.includes(filters.breed)&&<option value={filters.breed}>{filters.breed} (from shared search)</option>}{breeds.map(b=><option key={b} value={b}>{b}</option>)}</select></label>
 <label>Coat or pattern<select value={filters.coat} onChange={e=>patch({coat:e.target.value})}><option value="">Any coat or pattern</option>{filters.coat&&!coats.includes(filters.coat)&&<option value={filters.coat}>{filters.coat} (from shared search)</option>}{coats.map(c=><option key={c} value={c}>{c}</option>)}</select></label>
 <label className="check"><input type="checkbox" checked={filters.includeMissing} onChange={e=>patch({includeMissing:e.target.checked})}/>Include no longer listed</label><p className="filter-note">Filters use rescue-provided details. Missing coat or location information isn’t guessed from photos.</p></div></details></aside>
 <section id="results" className="results" aria-label="Cat inventory"><div className="results-toolbar"><div className="view-tabs"><button className={!filters.savedOnly?'active':''} aria-pressed={!filters.savedOnly} onClick={()=>patch({savedOnly:false})}>Explore cats</button><button className={filters.savedOnly?'active':''} aria-pressed={filters.savedOnly} onClick={()=>patch({savedOnly:true})}>Saved <span>{saved.size}</span></button></div><label className="sort-label">Sort by<select value={filters.sort} onChange={e=>patch({sort:e.target.value})}><option value="newest">Newly discovered</option><option value="youngest">Youngest first</option><option value="oldest">Oldest first</option><option value="name">Name A–Z</option><option value="recent">Recently seen</option></select></label></div>
 <div className="results-summary"><h2 aria-live="polite">{inventory?`${visible.length} ${visible.length===1?'cat':'cats'}${filters.savedOnly?' saved':''}`:'Loading cats…'}</h2><a href="#coverage">View coverage<ArrowUpRight size={14}/></a></div>
 {chips.length>0&&<div className="filter-chips" aria-label="Active filters">{chips.map(([key,value])=><button key={key} aria-label={`Remove ${key} filter: ${value}`} onClick={()=>patch({[key]:''})}>{value}<X size={12}/></button>)}</div>}
 {filters.savedOnly&&<p className="saved-note">Saved on this browser only. A saved cat may no longer be listed; use “Include no longer listed” to check.</p>}
 {(failed.length>0||staleCount>0)&&<div className="notice warning">{failed.length?`${failed.length} rescue ${failed.length===1?'feed is':'feeds are'} unavailable. Previously seen listings remain visible. `:''}{staleCount?`${staleCount} listings have not been seen in over 24 hours.`:''}<a href="#coverage">Source details</a></div>}
 {visible.length?<><div className="cat-grid">{visible.slice(0,limit).map(cat=><Card key={cat.key} cat={cat} saved={saved.has(cat.key)} onSave={()=>toggleSaved(cat.key)}/>)}</div><div className="pagination"><span>Showing {Math.min(limit,visible.length)} of {visible.length}</span>{limit<visible.length&&<button onClick={()=>setLimit(n=>n+24)}>Show 24 more cats<ChevronDown size={16}/></button>}</div></>:<div className="empty"><CatIcon size={44}/><h3>{!inventory?'Loading saved inventory':filters.savedOnly&&!saved.size?'Start your shortlist':'No cats match this search'}</h3><p>{!inventory?'Listings and source health will appear here.':filters.savedOnly&&!saved.size?'Tap the heart on any cat to keep them here.':'Try another age group or rescue, or include unknown ages.'}</p><button onClick={()=>setFilters({...defaults})}>Explore all cats</button></div>}
 </section></div>
 <section id="coverage" className="coverage"><details><summary><div><h2>Rescues & source coverage</h2><p>{connected.length} connected of {sources.length} configured sources. Initial coverage: Phoenix area.</p></div><ChevronDown size={22}/></summary><p className="coverage-note">Scan now checks only connected sources. Sources marked Not connected have no working integration and will not be checked by waiting or running another scan. Listings may change between checks. Confirm availability, fees and meeting locations directly with the rescue.</p><div className="table-wrap"><table><thead><tr><th>Source</th><th>Status</th><th>Listings</th><th>Last success</th></tr></thead><tbody>{sources.map(s=><tr key={s.id}><td><a href={safeUrl(s.url)} target="_blank" rel="noopener noreferrer">{s.name}<ExternalLink size={12}/></a><p>{s.message}</p></td><td><span className={`status ${s.status==='checked'?'good':''}`}>{s.connected?s.status.replace(/_/g,' '):'Not connected'}</span></td><td>{s.connected?s.count:'—'}</td><td>{date(s.lastSuccess)}</td></tr>)}</tbody></table></div></details></section>
 <section className="history"><details><summary><div><h2>Scan history</h2><p>Manual and scheduled scans use the same connected sources.</p></div><ChevronDown size={22}/></summary>{inventory?.runs.length?<ol>{inventory.runs.slice(0,12).map(r=><li key={r.id}><Clock size={17}/><div><strong>{date(r.startedAt)}</strong><span>{r.trigger==='manual'?'Manual scan':r.trigger==='scheduled'?'Scheduled scan':r.trigger} · {r.sources.length} sources</span></div><span>{r.status}<small>{r.newCount} newly discovered</small></span></li>)}</ol>:<p>No scans yet.</p>}</details></section>
 </main><footer><a className="brand" href="/"><CatIcon size={21}/>Soul Cat</a><p>Find a companion. Adopt through a rescue.</p><a href="https://github.com/cvstv/soul-cat" target="_blank" rel="noopener noreferrer">Open source on GitHub<ExternalLink size={13}/></a></footer></>;
}
