import { useEffect, useState } from 'react';
import { Cat as CatIcon, Search, RefreshCw, MapPin, ExternalLink, SlidersHorizontal, ArrowUpRight, Check, Clock } from 'lucide-react';
import type { Cat, Inventory } from './types';

const date = (value: string | null) => value ? new Intl.DateTimeFormat('en-US', { month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', timeZone: 'America/Phoenix' }).format(new Date(value)) : 'Not yet checked';
const safeUrl = (value: string | null) => { try { const url = new URL(value || ''); return ['http:', 'https:'].includes(url.protocol) ? url.href : undefined; } catch { return undefined; } };
const age = (value: number | null) => { const months = value === null ? null : Math.floor(value); return months === null ? 'Age unknown' : months < 12 ? `${months} month${months === 1 ? '' : 's'} old` : `${Math.floor(months / 12)} year${Math.floor(months / 12) === 1 ? '' : 's'}${months % 12 ? `, ${months % 12} mo` : ''} old`; };
const stale = (value: string) => Date.now() - new Date(value).getTime() > 86_400_000;

function CatCard({ cat }: { cat: Cat }) {
  const [brokenPhoto, setBrokenPhoto] = useState(false);
  const photo = safeUrl(cat.photo), link = safeUrl(cat.adoptionUrl);
  return <article className="cat-card">
    <div className="cat-photo">{photo && !brokenPhoto ? <img src={photo} alt={cat.name || 'Cat available for adoption'} loading="lazy" onError={() => setBrokenPhoto(true)} /> : <div className="no-photo"><CatIcon size={58} strokeWidth={1} /><span>Photo unavailable</span></div>}
      <span className={`photo-label ${cat.availability === 'not_listed' ? 'muted-label' : ''}`}>{cat.availability === 'not_listed' ? 'No longer listed' : 'Listed for adoption'}</span>
    </div>
    <div className="cat-body"><div className="cat-title"><h3>{cat.name || 'Name unknown'}</h3><span>{cat.sex || 'Sex unknown'}</span></div>
      <p className="cat-age">{age(cat.ageMonths)} <span aria-hidden="true">/</span> {cat.breed || 'Breed unknown'}</p>
      <p className="cat-place"><MapPin size={14} />{cat.city && cat.city !== 'Unknown' ? cat.city : 'Location not specified'}</p>
      <p className="shelter">{cat.shelter || 'Shelter unknown'}</p>
      <div className="cat-tags"><span>{cat.coat || 'Coat unknown'}</span>{cat.confirmation !== 'unknown' && <span>{cat.confirmation === 'confirmed' ? 'Tortie: source confirmed' : 'Tortie: visual match'}</span>}</div>
      <details><summary>Listing details</summary><p className="description">{cat.description || 'No description provided by this source.'}</p><dl className="cat-details"><dt>Location</dt><dd>{cat.location || 'Unknown'}</dd><dt>Adoption fee</dt><dd>{cat.adoptionFee || 'Not provided'}</dd><dt>Animal ID</dt><dd>{cat.animalId || 'Not provided'}</dd><dt>First seen</dt><dd>{date(cat.firstSeen)}</dd><dt>Last seen</dt><dd>{date(cat.lastSeen)}{stale(cat.lastSeen) ? ' (over 24 hours ago)' : ''}</dd></dl><p className="small">All times are Phoenix time. Confirm availability and details with the shelter.</p></details>
      <div className="cat-footer"><span className={stale(cat.lastSeen) ? 'stale' : 'fresh'}>{stale(cat.lastSeen) ? <Clock size={13} /> : <Check size={13} />}{stale(cat.lastSeen) ? 'Needs a fresh check' : 'Seen within 24h'}</span>{link ? <a href={link} target="_blank" rel="noopener noreferrer">Meet {cat.name || 'this cat'}<ArrowUpRight size={16} /></a> : <span className="small">Link unavailable</span>}</div>
    </div>
  </article>;
}

export default function App() {
  const [inventory, setInventory] = useState<Inventory | null>(null), [error, setError] = useState(''), [starting, setStarting] = useState(false);
  const [query, setQuery] = useState(''), [city, setCity] = useState(''), [minAge, setMinAge] = useState(''), [maxAge, setMaxAge] = useState(''), [sex, setSex] = useState(''), [breed, setBreed] = useState(''), [coat, setCoat] = useState(''), [confirmation, setConfirmation] = useState(''), [unknownAge, setUnknownAge] = useState(true), [includeMissing, setIncludeMissing] = useState(false);
  const load = async () => { try { const response = await fetch('/api/inventory'); if (!response.ok) throw new Error('Inventory could not be loaded. Try again.'); setInventory(await response.json()); setError(''); } catch (e) { setError(e instanceof Error ? e.message : 'Inventory could not be loaded.'); } };
  const running = inventory?.runs[0]?.status === 'running';
  useEffect(() => { void load(); }, []);
  useEffect(() => { if (!running && !starting) return; const id = window.setInterval(() => void load(), 3000); return () => window.clearInterval(id); }, [running, starting]);
  const refresh = async () => { setStarting(true); setError(''); try { const response = await fetch('/api/refresh', { method: 'POST' }); const body = await response.json(); if (!response.ok) throw new Error(body.error || 'Scan could not start.'); await load(); } catch (e) { setError(e instanceof Error ? e.message : 'Scan could not start.'); } finally { setStarting(false); } };
  const reset = () => { setQuery(''); setCity(''); setMinAge(''); setMaxAge(''); setSex(''); setBreed(''); setCoat(''); setConfirmation(''); setUnknownAge(true); setIncludeMissing(false); };
  const cats = inventory?.cats || [];
  const visible = cats.filter(cat => (includeMissing || cat.availability === 'listed') && (!query || cat.name.toLowerCase().includes(query.toLowerCase())) && (!city || cat.city === city) && (cat.ageMonths === null ? unknownAge : (!minAge || cat.ageMonths >= Number(minAge)) && (!maxAge || cat.ageMonths <= Number(maxAge))) && (!sex || cat.sex.toLowerCase().split('/')[0] === sex) && (!breed || cat.breed.toLowerCase().includes(breed.toLowerCase())) && (!coat || cat.coat.toLowerCase().includes(coat.toLowerCase().replace(/^tortie$/, 'tortoiseshell'))) && (!confirmation || cat.confirmation === confirmation));
  const cities = [...new Set(cats.map(cat => cat.city).filter(Boolean))].sort();
  const sources = inventory?.sources || [];
  return <><header className="topbar"><a className="brand" href="#"><span className="brand-icon"><CatIcon size={24} strokeWidth={1.6} /></span>Soul Cat<span className="brand-note">Adoption finder</span></a><a className="coverage-link" href="#coverage"><span className="dot" />Source coverage</a></header>
    <main><section className="intro"><div><p className="region"><MapPin size={15} />Phoenix metro, Arizona</p><h1>A little soul.<br />A place to call home.</h1><p className="intro-copy">Explore cats from the shelters and rescues connected below. Find your tortie, compare the details, and meet them at the source.</p></div><div className="scan-panel"><button className="primary" onClick={() => void refresh()} disabled={running || starting}><RefreshCw size={17} className={running || starting ? 'spin' : ''} />{running || starting ? 'Scanning sources…' : 'Scan now'}</button><p>Checks all connected sources</p><dl><dt>Last successful check</dt><dd>{date(inventory?.lastSuccess || null)}</dd><dt>Next scheduled check</dt><dd>{inventory?.nextCheck ? date(inventory.nextCheck) : 'Schedule unavailable'}</dd></dl><span className="small">Phoenix time (MST)</span></div></section>
      {error && <div className="error" role="alert">{error} <button onClick={() => void load()}>Retry loading</button></div>}
      <div className="inventory-heading"><h2>Find your companion</h2><p aria-live="polite">{inventory ? `${visible.length} ${visible.length === 1 ? 'cat' : 'cats'} in view` : 'Loading inventory…'}</p></div>
      <div className="inventory-layout"><aside className="filters" aria-label="Filter cats"><div className="filter-heading"><span><SlidersHorizontal size={16} /> Refine your search</span><button onClick={reset}>Reset</button></div><label>Name<div className="search-input"><Search size={16} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search cats" /></div></label><label>City<select value={city} onChange={e => setCity(e.target.value)}><option value="">All listed cities</option>{cities.map(value => <option key={value}>{value}</option>)}</select></label><fieldset><legend>Age in months</legend><div className="age-inputs"><label><span className="sr-only">Minimum age in months</span><input type="number" min="0" value={minAge} onChange={e => setMinAge(e.target.value)} placeholder="Min" /></label><span>to</span><label><span className="sr-only">Maximum age in months</span><input type="number" min="0" value={maxAge} onChange={e => setMaxAge(e.target.value)} placeholder="Max" /></label></div></fieldset><label className="checkbox"><input type="checkbox" checked={unknownAge} onChange={e => setUnknownAge(e.target.checked)} />Include unknown ages</label><label>Sex<select value={sex} onChange={e => setSex(e.target.value)}><option value="">Any sex</option><option value="female">Female</option><option value="male">Male</option><option value="unknown">Unknown</option></select></label><label>Breed<input value={breed} onChange={e => setBreed(e.target.value)} placeholder="Any breed" /></label><label>Coat<input value={coat} onChange={e => setCoat(e.target.value)} placeholder="e.g. tortoiseshell" /></label><label>Tortie confirmation<select value={confirmation} onChange={e => setConfirmation(e.target.value)}><option value="">All confidence levels</option><option value="confirmed">Source confirmed</option><option value="visual">Visual match</option><option value="unknown">Unconfirmed</option></select></label><label className="checkbox"><input type="checkbox" checked={includeMissing} onChange={e => setIncludeMissing(e.target.checked)} />Include no longer listed</label><p className="filter-note">Coat confirmation comes from shelter labels. Photo-based matching is not available yet.</p></aside>
        <section className="results" aria-label="Cat inventory"><div className="scope-note"><MapPin size={16} /><p><strong>Local listings, with clear limits.</strong> This inventory covers the connected Phoenix-area sources below. It does not search every shelter or nationwide listings.</p></div>{visible.length ? <div className="cat-grid">{visible.map(cat => <CatCard key={cat.key} cat={cat} />)}</div> : <div className="empty"><CatIcon size={48} strokeWidth={1} /><h3>{!inventory ? 'Gathering your inventory' : cats.length ? 'No cats match these filters' : 'Your next companion starts with a scan'}</h3><p>{!inventory ? 'Loading saved listings and source coverage.' : cats.length ? 'Try widening the age range, including unknown ages, or resetting your filters.' : 'Scan connected sources to collect current listings. Source errors and unavailable connections will appear below.'}</p>{cats.length > 0 && <button onClick={reset}>Reset filters</button>}</div>}</section></div>
      <section id="coverage" className="coverage"><div className="section-heading"><div><h2>Every source, in the open</h2><p>Coverage and check results for every configured shelter and rescue.</p></div><span>{sources.filter(source => source.connected).length} connected / {sources.length} configured</span></div><div className="table-wrap"><table><thead><tr><th>Source</th><th>Status</th><th>Listings</th><th>Last successful check</th></tr></thead><tbody>{sources.map(source => <tr key={source.id}><td>{safeUrl(source.url) ? <a href={safeUrl(source.url)} target="_blank" rel="noopener noreferrer">{source.name}<ExternalLink size={13} /></a> : <strong>{source.name}</strong>}<p>{source.message || (source.connected ? 'Connected source' : 'Not connected')}</p></td><td><span className={`status ${source.status === 'checked' || source.status === 'ok' || source.status === 'success' ? 'status-good' : ''}`}>{source.status.replace(/_/g, ' ')}</span>{!source.connected && <small>Not connected</small>}</td><td>{source.connected ? source.count : '—'}</td><td>{date(source.lastSuccess)}</td></tr>)}</tbody></table>{!sources.length && <p className="table-empty">{inventory ? 'No sources configured.' : 'Loading source coverage…'}</p>}</div></section>
      <section className="history"><h2>Scan history</h2><p>Results are retained across checks. A missing listing is marked “no longer listed” after a successful source check.</p>{inventory?.runs.length ? <ol>{inventory.runs.slice(0, 12).map(run => <li key={run.id}><Clock size={17} /><div><strong>{date(run.startedAt)}</strong><span>{run.trigger === 'manual' ? 'Manual scan' : run.trigger.replace(/_/g, ' ')}{run.finishedAt ? ` · Finished ${date(run.finishedAt)}` : run.status === 'running' ? ' · In progress' : ' · Did not finish'}</span></div><span className="history-result">{run.status.replace(/_/g, ' ')}<small>{run.newCount} new listings</small></span></li>)}</ol> : <p className="history-empty">No scans recorded yet.</p>}</section>
    </main><footer><span className="footer-brand"><CatIcon size={18} />Soul Cat</span><p>A thoughtful search for your next companion. Adoption details are confirmed by the shelter.</p></footer></>;
}
